DROP TABLE `adminEmailAuthorizations`;--> statement-breakpoint
DROP TABLE `classGroups`;--> statement-breakpoint
DROP TABLE `duplicateReviews`;--> statement-breakpoint
DROP TABLE `enrollments`;--> statement-breakpoint
DROP TABLE `externalSyncEvents`;--> statement-breakpoint
DROP TABLE `families`;--> statement-breakpoint
DROP TABLE `loyaltyCards`;--> statement-breakpoint
DROP TABLE `members`;--> statement-breakpoint
DROP TABLE `notificationPreferences`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `offers`;--> statement-breakpoint
DROP TABLE `parentUpdateRequests`;--> statement-breakpoint
DROP TABLE `paymentRequests`;--> statement-breakpoint
DROP TABLE `policyAcceptances`;--> statement-breakpoint
DROP TABLE `staffAccounts`;--> statement-breakpoint
DROP TABLE `staffAuditLogs`;--> statement-breakpoint
DROP TABLE `staffSessions`;--> statement-breakpoint
DROP TABLE `transactions`;--> statement-breakpoint
DROP TABLE `users`;